version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql://yourusername:yourpassword@db:5432/yourdbname
    ports:
      - "8000:8000"
    depends_on:
      - db
